version: '3'
services:
  rails-chat-tutorial-redis:
    ports:
      - "6379:6379"
    image: 'redis'
  rails-chat-tutorial-pg:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    image: 'postgres'
  rails-chat-tutorial-web:
    build: .
    environment:
      - DATABASE_HOST=172.17.0.1 
      - DATABASE_PORT=5432 
      - DATABASE_USERNAME=postgres 
      - DATABASE_PASSWORD=postgres 
      - REDIS_URL=redis://172.17.0.1:6379/1 
    ports:
      - "3000:3000"
    image: "rails-chat-tutorial"
    command: rails db:create
    command: rails db:migrate
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - rails-chat-tutorial-pg

